services:
  db: 
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build: 
      context: ./codeleap_challenge_api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./codeleap_challenge_api:/app
    env_file:
      - .env
    depends_on:
      - db
  
  app:
      build: 
        context: ./webapp/
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./webapp/src:/app/src
      env_file:
        - .env
      depends_on:
        - db
        - api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - api
      - app
    ports:
      - "9999:9999"
volumes:
  data:
  