services:
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=codeleap
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

    volumes:
      - data:/var/lib/postgresql/data

  api:
    image: andrebits/codeleap-api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-jg@vql)(4+5yd#dpa0c$&r=b)iag@csdppl0&3%sx%=(=o%b8@
    depends_on:
      - db
  
  app:
      image: andrebits/codeleap-webapp
      ports:
        - "3000:3000"
      environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_TELEMETRY_DISABLED=1
      depends_on:
        - db
        - api

      

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - api
      - app
    ports:
      - "9999:9999"
volumes:
  data:
  